// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNOR50WNx3UrkPoRfdCJ9MMDhypLnVUI',
    appId: '1:534285622526:web:2ae11c58e6139cb74299af',
    messagingSenderId: '534285622526',
    projectId: 'nyse-bites',
    authDomain: 'nyse-bites.firebaseapp.com',
    storageBucket: 'nyse-bites.firebasestorage.app',
    measurementId: 'G-P69S5P2KQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNOR50WNx3UrkPoRfdCJ9MMDhypLnVUI',
    appId: '1:534285622526:android:3e02082b41f71df428987b',
    messagingSenderId: '534285622526',
    projectId: 'nyse-bites',
    storageBucket: 'nyse-bites.firebasestorage.app',
  );
}